namespace SampleMauiApp;

public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();
    }

    async void OnRequestCamera(object? sender, EventArgs e)
        => await CheckAndDisplayAsync<Permissions.Camera>("Camera");

    async void OnRequestBluetooth(object? sender, EventArgs e)
    {
        // Bluetooth doesn't have a built-in MAUI permission type,
        // but the manifest entries are generated by MauiPermission.
        await DisplayAlert("Bluetooth LE",
            "Manifest permissions and Info.plist entries were generated at build time by Shiny.Permissions.MSBuild.",
            "OK");
    }

    async void OnRequestLocation(object? sender, EventArgs e)
        => await CheckAndDisplayAsync<Permissions.LocationWhenInUse>("Location");

    async void OnRequestPush(object? sender, EventArgs e)
    {
        // Push notification registration is platform-specific;
        // MauiPermission generates the required manifest/plist entries.
        await DisplayAlert("Push Notifications",
            "Manifest permissions and Info.plist entries were generated at build time by Shiny.Permissions.MSBuild.",
            "OK");
    }

    async void OnRequestBiometric(object? sender, EventArgs e)
    {
        await DisplayAlert("Biometric",
            "NSFaceIDUsageDescription and USE_BIOMETRIC permission were generated at build time by Shiny.Permissions.MSBuild.",
            "OK");
    }

    async void OnRequestContacts(object? sender, EventArgs e)
        => await CheckAndDisplayAsync<Permissions.ContactsRead>("Contacts");

    async Task CheckAndDisplayAsync<TPermission>(string name) where TPermission : Permissions.BasePermission, new()
    {
        var status = await Permissions.CheckStatusAsync<TPermission>();

        if (status != PermissionStatus.Granted)
        {
            status = await Permissions.RequestAsync<TPermission>();
        }

        await DisplayAlert(name, $"Permission status: {status}", "OK");
    }
}
